language: node_js
node_js:
- '6'
before_deploy:
- npm install -g serverless
- cd ./src && npm install && cd ..
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy && npm run deploy-dev
  on:
    branch: master