service: eviction-lab-exports
app: evictionlabzip
org: amygroshek
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  environment:
    export_bucket: eviction-lab-exports
    pdf_path: https://exports.evictionlab.org/pdf
    # pdf_path: http://localhost:3001 # Run both `npm run offline-zip` and `npm run offline-pdf` to use.
    stage: ${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::eviction-lab-exports/*"
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::eviction-lab-exports-dev/*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  # - serverless-domain-manager

package:
  individually: true
  exclude:
    - node_modules/**
  include:
    - ./assets
    - node_modules/aws-sdk/**

functions:
  xlsx:
    package:
      include:
        - node_modules/ms/**
        - node_modules/debug/**
        - node_modules/follow-redirects/**
        - node_modules/is-buffer/**
        - node_modules/axios/**
        - node_modules/xlsx/**
    memorySize: 2048
    timeout: 30
    handler: src/exports/xlsx.fileHandler
    events:
      - http:
          path: /xlsx
          method: post
          cors: true
  pptx:
    package:
      include:
        - node_modules/@mapbox/**
        - node_modules/d3-array/**
        - node_modules/d3-collection/**
        - node_modules/d3-color/**
        - node_modules/d3-format/**
        - node_modules/d3-interpolate/**
        - node_modules/d3-time/**
        - node_modules/d3-time-format/**
        - node_modules/d3-scale/**
        - node_modules/d3-path/**
        - node_modules/d3-shape/**
        - node_modules/nan/**
        - node_modules/css-font-size-keywords/**
        - node_modules/css-font-stretch-keywords/**
        - node_modules/css-font-style-keywords/**
        - node_modules/css-font-weight-keywords/**
        - node_modules/css-global-keywords/**
        - node_modules/css-list-helpers/**
        - node_modules/css-system-font-keywords/**
        - node_modules/tcomb/**
        - node_modules/unquote/**
        - node_modules/parse-css-font/**
        - node_modules/isnumeric/**
        - node_modules/viewport-dimensions/**
        - node_modules/units-css/**
        - node_modules/canvas-aws-prebuilt/**
        - node_modules/pptxgenjs/**
        - node_modules/ms/**
        - node_modules/debug/**
        - node_modules/follow-redirects/**
        - node_modules/is-buffer/**
        - node_modules/axios/**
    memorySize: 2048
    timeout: 30
    handler: src/exports/pptx.fileHandler
    events:
      - http:
          path: /pptx
          method: post
          cors: true
  zip:
    package:
      include:
        - node_modules/@mapbox/**
        - node_modules/handlebars/**
        - node_modules/pako/**
        - node_modules/core-js/**
        - node_modules/jszip/**
        - node_modules/xlsx/**
        - node_modules/d3-array/**
        - node_modules/d3-collection/**
        - node_modules/d3-color/**
        - node_modules/d3-format/**
        - node_modules/d3-interpolate/**
        - node_modules/d3-time/**
        - node_modules/d3-time-format/**
        - node_modules/d3-scale/**
        - node_modules/d3-path/**
        - node_modules/d3-shape/**
        - node_modules/nan/**
        - node_modules/css-font-size-keywords/**
        - node_modules/css-font-stretch-keywords/**
        - node_modules/css-font-style-keywords/**
        - node_modules/css-font-weight-keywords/**
        - node_modules/css-global-keywords/**
        - node_modules/css-list-helpers/**
        - node_modules/css-system-font-keywords/**
        - node_modules/tcomb/**
        - node_modules/unquote/**
        - node_modules/parse-css-font/**
        - node_modules/isnumeric/**
        - node_modules/viewport-dimensions/**
        - node_modules/units-css/**
        - node_modules/canvas-aws-prebuilt/**
        - node_modules/pptxgenjs/**
        - node_modules/ms/**
        - node_modules/debug/**
        - node_modules/follow-redirects/**
        - node_modules/is-buffer/**
        - node_modules/axios/**
    memorySize: 2048
    timeout: 30
    handler: src/exports/zip.fileHandler
    events:
      - http:
          path: /zip
          method: post
          cors: true

custom:
  optimize:
    includePaths:
      - ./assets

# custom:
#   customDomain:
#     domainName: 'exports.evictionlab.org'
#     certificateName: '*.evictionlab.org'
#     basePath: 'format'
#     stage: prod
#     createRoute53Record: true
