service: eviction-lab-exports

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    asset_bucket: eviction-lab-exports
    export_bucket: eviction-lab-exports

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::eviction-lab-exports/*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  individually: true
  exclude:
    - node_modules/**
  include:
    - node_modules/aws-sdk/**

functions:
  docx:
    package:
      include:
        - node_modules/handlebars/**
        - node_modules/pako/**
        - node_modules/core-js/**
        - node_modules/jszip/**
    timeout: 300
    handler: src/exports/docx.fileHandler
    events:
      - http:
          path: /docx
          method: post
  xlsx:
    package:
      include:
        - node_modules/xlsx/**
    timeout: 300
    handler: src/exports/xlsx.fileHandler
    events:
      - http:
          path: /xlsx
          method: post
  pptx:
    package:
      include:
        - node_modules/pptxgenjs/**
    timeout: 300
    handler: src/exports/pptx.fileHandler
    events:
      - http:
          path: /pptx
          method: post
