service: eviction-lab-exports

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    asset_bucket: eviction-lab-exports
    export_bucket: eviction-lab-exports

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::eviction-lab-exports/*"

functions:
  pdf:
    timeout: 300
    handler: exports/pdf.fileHandler
    events:
      - http:
          path: /pdf
          method: post
  docx:
    timeout: 300
    handler: exports/docx.fileHandler
    events:
      - http:
          path: /docx
          method: post
  xlsx:
    timeout: 300
    handler: exports/xlsx.fileHandler
    events:
      - http:
          path: /xlsx
          method: post
  pptx:
    timeout: 300
    handler: exports/pptx.fileHandler
    events:
      - http:
          path: /pptx
          method: post
  png:
    timeout: 300
    handler: exports/png.fileHandler
    events:
      - http:
          path: /png
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-offline