service: eviction-lab-exports

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    asset_bucket: eviction-lab-exports
    export_bucket: eviction-lab-exports

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::eviction-lab-exports/*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-chrome

functions:
  pdf:
    package:
      include:
        - node_modules/@serverless-chrome/**
        - node_modules/chrome-launcher/**
        - node_modules/chrome-remote-interface/**
        - node_modules/chromeless/**
      exclude:
        - ""
    timeout: 300
    handler: exports/pdf.fileHandler
    events:
      - http:
          path: /pdf
          method: post
  docx:
    timeout: 300
    handler: exports/docx.fileHandler
    package:
      exclude:
        - node_modules/@serverless-chrome/**
        - node_modules/chrome-launcher/**
        - node_modules/chrome-remote-interface/**
        - node_modules/chromeless/**
    events:
      - http:
          path: /docx
          method: post
  xlsx:
    timeout: 300
    handler: exports/xlsx.fileHandler
    package:
      exclude:
        - node_modules/@serverless-chrome/**
        - node_modules/chrome-launcher/**
        - node_modules/chrome-remote-interface/**
        - node_modules/chromeless/**
    events:
      - http:
          path: /xlsx
          method: post
  pptx:
    timeout: 300
    handler: exports/pptx.fileHandler
    package:
      exclude:
        - node_modules/@serverless-chrome/**
        - node_modules/chrome-launcher/**
        - node_modules/chrome-remote-interface/**
        - node_modules/chromeless/**
    events:
      - http:
          path: /pptx
          method: post
