service: eviction-lab-exports

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    - ASSET_BUCKET: ${env:ASSET_BUCKET}
    - EXPORT_BUCKET: ${env:EXPORT_BUCKET}

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:*"
      Resource: "arn:aws:s3:::eviction-lab-exports/*"

functions:
  pdf:
    timeout: 300
    handler: exports/pdf.default
    events:
      - http:
          path: /pdf
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-chrome
  - serverless-offline