export const Translations: Object = {
    'en': {
        'EXPORT': {
            'TITLE_INTRO': () => 'UNDERSTANDING EVICTION IN',
            'TITLE_SOURCE': () => 'A PowerPoint Presentation generated by The Eviction Lab at Princeton University',
            'TITLE_SOURCE_PDF': () => 'A Presentation generated by The Eviction Lab at Princeton University',
            'TITLE_EXTRACT_DATE': () => `Data extracted on ${new Date().toISOString().slice(0, 10)}`,
            'TITLE_WEB_LINK': () => 'For further information, visit evictionlab.org',
            'UNAVAILABLE': () => 'Unavailable',
            'EVICTION': () => 'Eviction',
            'EVICTIONS': () => 'Evictions',
            'EVICTION_FILING': () => 'Eviction Filing',
            'EVICTION_FILINGS': () => 'Eviction Filings',
            'EVICTION_RATE': () => 'Eviction Rate',
            'EVICTION_FILING_RATE': () => 'Eviction Filing Rate',
            'EVICTION_RATES': () => 'Eviction Rates',
            'EVICTION_FILING_RATES': () => 'Eviction Filing Rates',
            'EVICTIONS_PER_DAY': () => 'Evictions Per Day',
            'FEATURE_TITLE': (name, total, kind, year) => `${name} experienced ${total} ${kind} in ${year}`,
            'FEATURE_TITLE_UNAVAILABLE': (name, kind, year) => `${year} ${kind} data for ${name} is unavailable`,
            'FEATURE_BULLET_ONE': (total) => `Number of evictions per day: ${total}`,
            'FEATURE_BULLET_ONE_PDF': () => `Number of evictions per day:`,
            'FEATURE_BULLET_TWO': (rateDesc, rate) => `${rateDesc}: ${rate}*`,
            'FEATURE_EVICTION_RATE_DESCRIPTION': () => '* An eviction rate is the number of evictions per 100 renter-occupied households',
            'FEATURE_EVICTION_FILING_RATE_DESCRIPTION': () => '* An eviction filing rate is the number of eviction filings per 100 renter-occupied households',
            'DEMOGRAPHIC_BREAKDOWN': () => 'Census Demographics',
            'TITLE_FACTS_ABOUT': () => 'Facts About Evictions',
            'BAR_CHART_TITLE': (subject, year) => `Comparison of ${subject} in ${year}`,
            'LINE_CHART_TITLE': (subject) => `Comparison of ${subject} over time`,
            'NO_DATA': () => 'No data',
            'FLAG_99TH': () => 'This area has an eviction/filing rate in the top 1%. Please see our FAQ section to better understand why https://evictionlab.org/help-faq/',
            'FLAG_LOW': () => 'This area\'s estimated eviction/filing rate is too low. Please see our FAQ section to better understand why https://evictionlab.org/help-faq/',
            'FLAG_MARYLAND_FILING': () => 'Because of the way Maryland records eviction notices, it has a much higher filing rate than everywhere else. Please see our FAQ section to better understand why https://evictionlab.org/help-faq/',
            'FLAG_MARYLAND_EXPL': () => 'Because of the way Maryland records eviction notices, it has a much higher filing rate than everywhere else.',
            'FLAG_MARYLAND_SEE': () => 'Please see our FAQ section to better understand these issues https://evictionlab.org/help-faq/',
            'TRACT_SINGULAR': () => 'Census Tract',
            'BLOCK_GROUP_SINGULAR': () => 'Block Group',
            'MAX_ABBREV': () => 'Max',
            'MIN_ABBREV': () => 'Min',
            'CONFIDENCE_INTERVAL': () => 'Confidence Interval',
            'TOO_LOW': () => 'Eviction/filing rate is too low.',
            'TOP_1_PERC': () => 'Eviction/filing rate in the top 1%.',
            'TITLE_COMPARISON_OF': () => 'Comparison of',
            'TITLE_OVER_TIME': () => 'Over Time',
            'TITLE_EVICTIONS_PER_DAY': () => 'Evictions per Day',
            'TITLE_EVICTION_RATE': () => 'Eviction Rate',
            'REPORT_PROSE_1': () => { return '<div class="section">' +
                '<p>What is an eviction?</p>' +
                '<p>An eviction happens when a landlord expels people from property they own. Evictions are landlord-initiated involuntary moves that happen to renters, whereas foreclosures are involuntary moves that happen to homeowners when a bank or other lending agency repossesses a home.</p>' +
              '</div>' +
              '<div class="section">' +
                '<p>Why do people get evicted?</p>' +
                '<p>Most evictions happen because renters cannot or do not pay their rent. Landlords can evict renters for a number of other reasons, too, including taking on boarders, damaging property, causing a disturbance, or breaking the law. In most American cities and towns, landlords can evict renters even if they have not missed a rent payment or otherwise violated their lease agreement; these are called “no fault” evictions.</p>' +
              '</div>' +
              '<div class="section">' +
                '<p>What is the relationship between the affordable housing crisis and the eviction epidemic?</p>' +
                '<p>Today, most poor renting families spend at least half of their income on housing costs, with one in four of those families spending over 70 percent of their income just on rent and utilities. Incomes for Americans of modest means have flatlined while housing costs have soared. Only one in four families who qualifies for affordable housing programs gets any kind of help. Under those conditions, it has become harder for low-income families to keep up with rent and utility costs, and a growing number are living one misstep or emergency away from eviction.</p>' +
              '</div>' +
              '<div class="section">' +
                '<p>What is the eviction process like?</p>' +
                '<p>Landlords initiate the process, and renters are served notice to appear in court. Almost everywhere in the United States, evictions take place in civil court, where renters have no right to an attorney. For this reason and others, most renters do not appear in eviction court. When this happens, they receive a default eviction judgement, provided that the landlord or a representative is present. Renters who do appear in court may also receive an eviction judgement ordering them to vacate their home by a specific date. Eviction cases can be resolved in other ways as well. For one, the case may be dismissed or ruled in favor of defendants, allowing renter to remain in their home. In addition, a mediated agreement can be established between a landlord and a renter, often called a “settlement” or “stipulation,” which comes with certain terms. If renters meet the terms, the eviction is dismissed; if they do not, an eviction judgment can be rendered. In the event that evicted renters do not leave their home by the specified date, their landlord may file a “writ of restitution,” which permits law enforcement officers to forcibly remove a family and often their belongings.</p>' +
              '</div>';
            },
            'REPORT_PROSE_2': () => {
              return '<div class="section">' +
                '<p>Who is at most risk of eviction?</p>' +
                '<p>Low-income women, especially poor women of color, have a high risk of eviction. Research has shown domestic violence victims and families with children are also at particularly high risk for eviction.</p>' +
              '</div>' +
              '<div class="section">' +
                '<p>How does an eviction affect someone’s life?</p>' +
                '<p>Eviction causes a family to lose their home. They often are also expelled from their community and their children have to switch schools. Families regularly lose their possessions, too, which are piled on the sidewalk or placed in storage, only to be reclaimed after paying a fee. A legal eviction comes with a court record, which can prevent families from relocating to decent housing in a safe neighborhood, because many landlords screen for recent evictions. Studies also show that eviction causes job loss, as the stressful and drawn-out process of being forcibly expelled from a home causes people to make mistakes at work and lose their job. Eviction also has been shown to affect people\'s mental health: one study found that mothers who experienced eviction reported higher rates of depression two years after their move. The evidence strongly indicates that eviction is not just a condition of poverty, it is a cause of it.</p>' +
            '</div>' +
            '<p class="info">For further information, visit evictionlab.org</p>';
          }
        },
        'DATA_PROPS': {
            'e': 'Evictions',
            'efr': 'Eviction Filing Rate',
            'ef': 'Eviction Filings',
        },
        'DEM_DATA_PROPS': {
            'p': 'Population',
            'pro': '% Renter-Occupied Households',
            'pr': 'Poverty Rate',
            'mgr': 'Median Gross Rent',
            'mhi': 'Median Household Income',
            'mpv': 'Median Property Value',
            'rb': 'Rent Burden',
            'paa': 'Black',
            'pw': 'White',
            'ph': 'Hispanic/Latinx',
            'pa': 'Asian',
            'pai': 'American Indian/Alaska Native',
            'pnp': 'Native Hawaiian/Pacific Islander',
            'pm': 'Multiple Races',
            'po': 'Other Races'
        },
        'CODEBOOK': {
            'DISCLAIMER': 'NOTE: Demographic variables are provided for context, but do not change every year because they are pulled from the 2000 and 2010 Census, as well as the 2009, 2012, and 2015 American Community Survey 5-year estimates',
            'VALUES': [
                {
                    'Column': 'GEOID',
                    'Description': 'Census FIPS code for 2010 geography'
                },
                {
                    'Column': 'name',
                    'Description': 'Census location name'
                },
                {
                    'Column': 'parent-location',
                    'Description': 'Parent location in Census hierarchy'
                },
                {
                    'Column': 'population',
                    'Description': 'Total population'
                },
                {
                    'Column': 'poverty-rate',
                    'Description': '% of the population with income in the last 12 months below the poverty level'
                },
                {
                    'Column': 'pct-renter-occupied',
                    'Description': '% of occupied housing units that are renter-occupied'
                },
                {
                    'Column': 'median-gross-rent',
                    'Description': 'Median gross rent'
                },
                {
                    'Column': 'median-household-income',
                    'Description': 'Median household income'
                },
                {
                    'Column': 'median-property-value',
                    'Description': 'Median property value'
                },
                {
                    'Column': 'rent-burden',
                    'Description': 'Median gross rent as a percentage of household income. The max value is 50%, representing >= 50%'
                },
                {
                    'Column': 'pct-white',
                    'Description': '% population that is White alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-af-am',
                    'Description': '% population that is Black or African American alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-hispanic',
                    'Description': '% population that is of Hispanic or Latino origin'
                },
                {
                    'Column': 'pct-am-ind',
                    'Description': '% population that is American Indian and Alaska Native alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-asian',
                    'Description': '% population that is Asian alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-nh-pi',
                    'Description': '% population that is Native Hawaiian and Other Pacific Islander alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-other',
                    'Description': '% population that is other race alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-multiple',
                    'Description': '% population that is two or more races and not Hispanic or Latino'
                },
                {
                    'Column': 'evictions',
                    'Description': 'Number of eviction judgments in which renters were ordered to leave in a given area and year. Only counts a single address which received an eviction judgment per year.'
                },
                {
                    'Column': 'eviction-filings',
                    'Description': 'All eviction cases filed in an area, including multiple cases filed against the same address in the same year'
                },
                {
                    'Column': 'eviction-rate',
                    'Description': 'Ratio of the number of renter-occupied households in an area that received an eviction judgement in which renters were ordered to leave. Only counts a single address which received an eviction judgment per year.'
                },
                {
                    'Column': 'eviction-filing-rate',
                    'Description': 'Ratio of the number of evictions filed in an area over the number of renter-occupied homes in that area. Counts all eviction cases filed in an area, including multiple cases filed against the same address in the same year.'
                },
                {
                    'Column': 'evictions-per-day',
                    'Description': 'The number of eviction judgments per day'
                }
            ]
        }
    },
    'es': {
        'EXPORT': {
            'TITLE_INTRO': () => 'COMPRENDER EL DESALOJO EN',
            'TITLE_SOURCE': () => 'Una presentación de PowerPoint generada por The Eviction Lab en la Universidad de Princeton',
            'TITLE_SOURCE_PDF': () => 'Una presentación generada por The Eviction Lab en la Universidad de Princeton',
            'TITLE_EXTRACT_DATE': () => `Datos extraídos el ${new Date().toISOString().slice(0, 10)}`,
            'TITLE_WEB_LINK': () => 'Para más información, visite evictionlab.org',
            'UNAVAILABLE': () => 'No disponible',
            'EVICTION': () => 'Desalojo',
            'EVICTIONS': () => 'Desalojos',
            'EVICTION_FILING': () => 'Presentacion de desalojo',
            'EVICTION_FILINGS': () => 'Presentaciones de desalojo',
            'EVICTION_RATE': () => 'Tasa de desalojo',
            'EVICTION_FILING_RATE': () => 'Tasa de presentaciones de desalojo',
            'EVICTION_RATES': () => 'Tasas de desalojo',
            'EVICTION_FILING_RATES': () => 'Tasas de presentaciones de desalojo',
            'EVICTIONS_PER_DAY': () => 'Desalojos por día',
            'FEATURE_TITLE': (name, total, kind, year) => `${name} experimentó ${total} ${kind} en ${year}`,
            'FEATURE_TITLE_UNAVAILABLE': (name, kind, year) => `Los datos del año ${year} de ${kind} para ${name} no están disponibles`,
            'FEATURE_BULLET_ONE': (total) => `Número de desalojos por día: ${total}`,
            'FEATURE_BULLET_ONE_PDF': () => `Número de desalojos por día:`,
            'FEATURE_BULLET_TWO': (rateDesc, rate) => `${rateDesc}: ${rate}*`,
            'FEATURE_EVICTION_RATE_DESCRIPTION': () => 'Una tasa de desalojo es el número de desalojos por cada 100 viviendas ocupadas por inquilinos',
            'FEATURE_EVICTION_FILING_RATE_DESCRIPTION': () => 'Una tasa de presentación de desalojo es la cantidad de presentaciones de desalojo por cada 100 viviendas ocupadas por inquilinos',
            'DEMOGRAPHIC_BREAKDOWN': () => 'Desglose Demográfico',
            'TITLE_FACTS_ABOUT': () => 'Hechos sobre el desalojo',
            'BAR_CHART_TITLE': (subject, year) => `Comparación de las ${subject} en ${year}`,
            'LINE_CHART_TITLE': (subject) => `Comparación de las ${subject} a lo largo del tiempo`,
            'NO_DATA': () => 'Sin datos',
            'FLAG_99TH': () => 'Esta área tiene una tasa de desalojo/presentaciones en el 1% superior. Por favor, consulte nuestra sección de preguntas frecuentes para comprender mejor por qué https://evictionlab.org/en/help-faq/',
            'FLAG_LOW': () => 'La estimación de la tasa de desalojo/presentaciones de esta área es demasiado baja. Por favor, consulte nuestra sección de preguntas frecuentes para comprender mejor por qué https://evictionlab.org/en/help-faq/',
            'FLAG_MARYLAND_FILING': () => 'Debido a la forma en que Maryland registra los avisos de desalojo, tiene una tasa de presentación mucho más alta que en cualquier otro lugar. Por favor, consulte nuestra sección de preguntas frecuentes para comprender mejor por qué https://evictionlab.org/en/help-faq/',
            'FLAG_MARYLAND_EXPL': () => 'Debido a la forma en que Maryland registra los avisos de desalojo, tiene una tasa de presentación mucho más alta que en cualquier otro lugar.',
            'FLAG_MARYLAND_SEE': () => 'Por favor, consulte nuestra sección de preguntas frecuentes para comprender mejor por qué https://evictionlab.org/es/help-faq/',
            'TRACT_SINGULAR': () => 'Sección Censal',
            'BLOCK_GROUP_SINGULAR': () => 'Grupo de Cuadras',
            'MAX_ABBREV': () => 'MÁX',
            'MIN_ABBREV': () => 'MÍN',
            'CONFIDENCE_INTERVAL': () => 'Intervalo de Confianza',
            'TOO_LOW': () => 'La tasa de desalojo/presentaciones de esta área es demasiado baja.',
            'TOP_1_PERC': () => 'La tasa de desalojo/presentaciones en el 1% superior.',
            'TITLE_COMPARISON_OF': () => 'Comparación de las',
            'TITLE_OVER_TIME': () => 'a lo largo del tiempo',
            'TITLE_EVICTIONS_PER_DAY': () => 'Desalojos por Día',
            'TITLE_EVICTION_RATE': () => 'Tasa de desalojo',
            'REPORT_PROSE_1': () => {
              return '<div class="section">' +
                  '<p>¿Qué es un desalojo?</p>' +
                  '<p>Un desalojo ocurre cuando un propietario expulsa a las personas de la propiedad que posee. Los desalojos son movimientos involuntarios iniciados por el propietario que suceden a inquilinos, mientras que las ejecuciones hipotecarias son movimientos involuntarios que suceden a los propietarios cuando un banco u otra agencia de préstamos recupera un hogar.</p>' +
                '</div>' +
                '<div class="section">' +
                  '<p>¿Por qué las personas son desalojadas?</p>' +
                  '<p>La mayoría de los desalojos ocurren porque los inquilinos no pueden pagar o no pagan el alquiler. Los propietarios también pueden desalojar a los inquilinos por varias otras razones, como la contratación de internos, el daño a la propiedad, causar disturbios o infringir la ley. En la mayoría de las ciudades y pueblos de Estados Unidos, los propietarios pueden desalojar a los inquilinos, incluso si no han perdido el pago de la renta o han violado el contrato de arrendamiento; estos se llaman desalojos "sin culpa".</p>' +
                '</div>' +
                '<div class="section">' +
                  '<p>¿Cuál es la relación entre la crisis de vivienda asequible y la epidemia de desalojo?</p>' +
                  '<p>Hoy en día, la mayoría de las familias pobres que alquilan gastan al menos la mitad de sus ingresos en costos de vivienda, y una de cada cuatro de esas familias gasta más del 70 por ciento de sus ingresos en alquileres y servicios públicos. Los ingresos de los estadounidenses de medios modestos se han reducido, mientras que los costos de la vivienda se han disparado. Solo una de cada cuatro familias que califica para programas de vivienda asequible recibe ayuda de algún tipo. Bajo esas condiciones, se ha vuelto más difícil para las familias de bajos ingresos mantenerse al día con los costos de alquiler y servicios públicos, y un número cada vez mayor está viviendo un paso en falso o una emergencia lejos del desalojo.</p>' +
                '</div>' +
                '<div class="section">' +
                  '<p>¿Cómo es el proceso de desalojo?</p>' +
                  '<p>Los propietarios inician el proceso y se notifican a los inquilinos para que se presenten ante el tribunal. Casi en todas partes en los Estados Unidos, los desalojos tienen lugar en un tribunal civil, donde los inquilinos no tienen derecho a un abogado. Por esta razón y otras, la mayoría de los inquilinos no aparecen en el tribunal de desalojo. Cuando esto sucede, reciben un juicio de desalojo por defecto, siempre que el propietario o un representante esté presente. Los inquilinos que comparecen ante el tribunal también pueden recibir una sentencia de desalojo que les ordena abandonar su hogar antes de una fecha específica. Los casos de desalojo se pueden resolver de otras maneras también. Por un lado, el caso puede desestimarse o fallar a favor de los acusados, lo que permite que el arrendatario permanezca en su hogar.</p>' +
              '</div>';
            },
            'REPORT_PROSE_2': () => {
              return '<div class="section">' +
                  '<p></p><br>' +
                  '<p>Además, se puede establecer un acuerdo mediado entre un propietario y un arrendatario, a menudo llamado "acuerdo" o "estipulación", que viene con ciertos términos. Si los inquilinos cumplen con los términos, se desestima el desalojo; si no lo hacen, se puede emitir un juicio de desalojo. En caso de que los inquilinos desalojados no salgan de su hogar antes de la fecha especificada, el propietario puede presentar un "recurso de restitución" que permite a los agentes policiales expulsar por la fuerza a una familia y, a menudo, a sus pertenencias.</p>' +
              '</div>' +
              '<div class="section">' +
                  '<p>¿Quién corre mayor riesgo de ser desalojado?</p>' +
                  '<p>Las mujeres de bajos ingresos, especialmente las mujeres de color pobres, tienen un alto riesgo de desalojo. La investigación ha demostrado que las víctimas de violencia doméstica y las familias con niños también corren un riesgo particularmente alto de desalojo.</p>' +
              '</div>' +
              '<div class="section">' +
                  '<p>¿Cómo afecta un desalojo a la vida de alguien?</p>' +
                  '<p>El desalojo hace que una familia pierda su hogar. A menudo también son expulsados de su comunidad y sus hijos tienen que cambiar de escuela. Las familias también pierden regularmente sus pertenencias, que se amontonan en la acera o se almacenan, solo para ser recuperadas después de pagar una tarifa. Un desalojo legal viene con un registro judicial, que puede evitar que las familias se reubiquen en viviendas dignas en un vecindario seguro, ya que muchos propietarios filtran los recientes desalojos. Los estudios también muestran que el desalojo causa la pérdida de empleo, ya que el proceso estresante y prolongado de ser expulsado por la fuerza de un hogar hace que las personas cometan errores en el trabajo y pierdan su trabajo. También se ha demostrado que el desalojo afecta la salud mental de las personas: un estudio encontró que las madres que experimentaron el desalojo reportaron tasas más altas de depresión dos años después de su mudanza. La evidencia indica claramente que el desalojo no es solo una condición de pobreza, sino que es una causa de ello.</p>' +
              '</div>' +
              '<p class="info">Para más información, visite evictionlab.org</p>';
          }
        },
        'DATA_PROPS': {
            'e': 'Desalojos',
            'efr': 'Tasa de presentaciones de desalojo',
            'ef': 'Presentaciones de desalojo'
        },
        'DEM_DATA_PROPS': {
            'p': 'Población',
            'pro': '% Casas ocupadas por inquilinos',
            'pr': 'Tasa de pobreza',
            'mgr': 'Renta bruta mediana',
            'mhi': 'Ingreso bruto mediano',
            'mpv': 'Valor de propiedad mediano',
            'rb': 'Carga del alquiler',
            'paa': 'Negro',
            'pw': 'Blanco',
            'ph': 'Hispano/Latinx',
            'pa': 'Asiático',
            'pai': 'Indígena/Nativo de Alaska',
            'pnp': 'Nativo de Hawaii/Isleños del Pacífico',
            'pm': 'Dos o más razas',
            'po': 'Otra Raza'
        },
        'CODEBOOK': {
            'DISCLAIMER': 'NOTE: Demographic variables are provided for context, but do not change every year because they are pulled from the 2000 and 2010 Census, as well as the 2009, 2012, and 2015 American Community Survey 5-year estimates',
            'VALUES': [
                {
                    'Column': 'GEOID',
                    'Description': 'Census FIPS code for 2010 geography'
                },
                {
                    'Column': 'name',
                    'Description': 'Census location name'
                },
                {
                    'Column': 'parent-location',
                    'Description': 'Parent location in Census hierarchy'
                },
                {
                    'Column': 'population',
                    'Description': 'Total population'
                },
                {
                    'Column': 'poverty-rate',
                    'Description': '% of the population with income in the last 12 months below the poverty level'
                },
                {
                    'Column': 'pct-renter-occupied',
                    'Description': '% of occupied housing units that are renter-occupied'
                },
                {
                    'Column': 'median-gross-rent',
                    'Description': 'Median gross rent'
                },
                {
                    'Column': 'median-household-income',
                    'Description': 'Median household income'
                },
                {
                    'Column': 'median-property-value',
                    'Description': 'Median property value'
                },
                {
                    'Column': 'rent-burden',
                    'Description': 'Median gross rent as a percentage of household income. The max value is 50%, representing >= 50%'
                },
                {
                    'Column': 'pct-white',
                    'Description': '% population that is White alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-af-am',
                    'Description': '% population that is Black or African American alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-hispanic',
                    'Description': '% population that is of Hispanic or Latino origin'
                },
                {
                    'Column': 'pct-am-ind',
                    'Description': '% population that is American Indian and Alaska Native alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-asian',
                    'Description': '% population that is Asian alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-nh-pi',
                    'Description': '% population that is Native Hawaiian and Other Pacific Islander alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-other',
                    'Description': '% population that is other race alone and not Hispanic or Latino'
                },
                {
                    'Column': 'pct-multiple',
                    'Description': '% population that is two or more races and not Hispanic or Latino'
                },
                {
                    'Column': 'evictions',
                    'Description': 'Number of eviction judgments in which renters were ordered to leave in a given area and year. Only counts a single address which received an eviction judgment per year.'
                },
                {
                    'Column': 'eviction-filings',
                    'Description': 'All eviction cases filed in an area, including multiple cases filed against the same address in the same year'
                },
                {
                    'Column': 'eviction-rate',
                    'Description': 'Ratio of the number of renter-occupied households in an area that received an eviction judgement in which renters were ordered to leave. Only counts a single address which received an eviction judgment per year.'
                },
                {
                    'Column': 'eviction-filing-rate',
                    'Description': 'Ratio of the number of evictions filed in an area over the number of renter-occupied homes in that area. Counts all eviction cases filed in an area, including multiple cases filed against the same address in the same year.'
                },
                {
                    'Column': 'evictions-per-day',
                    'Description': 'The number of eviction judgments per day'
                }
            ]
        }
    }
};
