const pptx = require("pptxgenjs");

const titleSlide = pptx.addNewSlide({ bkgd: '6B8890' });

titleSlide.addText('UNDERSTANDING EVICTION IN [REGION]', {
    align: 'center',
    x: '20%',
    y: '25%',
    w: '60%',
    h: '25%',
    color: 'FF0000',
    fill: 'FFFFFF',
    font_size: 35,
    isTextBox: true
});

titleSlide.addText(
    'A PowerPoint Presentation generated by The Eviction Lab at Princeton University\n'+ 
    'For more information, go to www.evictionlab.org', {
        align: 'center',
        x: '25%',
        y: '55%',
        w: '50%',
        h: '25%',
        color: 'FFFFFF',
        font_size: 19,
        isTextBox: true
    }
);

titleSlide.addText(
    [
        { text: 'Source: ', options: { font_size: 12, color: 'ffffff', align: 'l', breakLine: false } },
        { text: 'The Eviction Lab at Princeton University: www.evictionlab.org. Data extracted on [DATE]', options: { font_size: 12, color: 'ffffff', align: 'l' } }
    ],
    { x: '5%', y: '90%', w: '90%', h: '7.5%' }
);

const slideOne = pptx.addNewSlide({ bkgd: 'f2f2f2' });

pptx.save('test');