import * as fs from 'fs';
import { Feature } from '../data/feature';
import { Export } from './export';
import { handler } from './handler';
import * as pptx from 'pptxgenjs';

export class PptxExport extends Export {
  fileExt = 'pptx';

  constructor(features: Array<Feature>) {
    super(features);
    this.key = this.createKey(features);
  };

  createSlide(feature: Feature): void {
    const titleSlide = pptx.addNewSlide({ bkgd: '6B8890' });

    titleSlide.addText('UNDERSTANDING EVICTION IN [REGION]', {
      align: 'center',
      x: 1.21,
      y: 2.61,
      w: 7.59,
      h: 1.8,
      color: '000000',
      fill: 'FFFFFF',
      font_size: 35,
      isTextBox: true
    });

    titleSlide.addText(
      'A PowerPoint Presentation generated by The Eviction Lab at Princeton University\n' +
      'For more information, go to www.evictionlab.org', {
        align: 'center',
        x: 2.21,
        y: 4.76,
        w: 5.58,
        h: 1.36,
        color: 'FFFFFF',
        font_size: 19,
        isTextBox: true
      }
    );

    titleSlide.addText(
      [
        { text: 'Source: The Eviction Lab at Princeton University: www.evictionlab.org. Data extracted on [DATE]', options: { font_size: 12, color: 'ffffff', align: 'c' } }
      ],
      { x: 0.55, y: 7.06, w: 8.91, h: 0.33 }
    );

    const slideOne = pptx.addNewSlide({ bkgd: 'f2f2f2' });

    slideOne.addText(
      '[REGION] EXPERIENCED [NUMBER] OF EVICTIONS IN [MOST RECENT YEAR]',
      {
        align: 'center',
        x: 1.75,
        y: 0.21,
        w: 6.49,
        h: 1.3,
        color: '000000',
        fill: 'FFFFFF',
        font_size: 28,
        isTextBox: true
      }
    );

    slideOne.addText(
      [
        {
          text: 'This amounts to [Number] of evictions per day',
          options: { bullet: true }
        },
        {
          text: 'In neighborhoods where the poverty rate exceeds 20%, that ratio is 1 in [NUMBER]',
          options: { bullet: true }
        },
        {
          text: 'Below is a graph of estimated eviction rates in [Region] over the last six years',
          options: { bullet: true }
        }
      ],
      { x: 0.54, y: 1.64, w: 9, h: 4.95, color: '000000', margin: 1 }
    );

    slideOne.addChart(pptx.charts.BAR, [{
      name: 'Eviction Rate',
      labels: ['2010', '2011', '2012', '2013', '2014', '2015'],
      values: [0.04, 0.032, 0.021, 0.045, 0.05, 0.04]
    }], {
        x: 1.56,
        y: 2.8,
        h: 3.37,
        w: 7.09,
        valAxisLabelFormatCode: '#%',
        chartColors: ['f6a21d'],
        showTitle: true,
        title: 'Eviction Rates in [AREA]',
        titleAlign: 'center'
      }
    );

    slideOne.addText(
      [
        { text: 'Source: The Eviction Lab at Princeton University: www.evictionlab.org. Data extracted on [DATE]', options: { font_size: 12, color: '000000', align: 'c' } }
      ],
      { x: 0.55, y: 7.06, w: 8.91, h: 0.33 }
    );
  }

  async createFile(): Promise<Buffer> {
    this.features.forEach((f) => this.createSlide(f));

    await pptx.save('ev_presentation', null, null);
    return fs.readFileSync('ev_presentation.pptx');
  }
}

export async function fileHandler(event, context, callback): Promise<void> {
  return await handler(PptxExport, event, context, callback);
}